print("3장 연습문제 1번")
a = int(input("첫 번째 정수를 입력해주세요 : "))
b = int(input("두 번째 정수를 입력해주세요 : "))

print("두 수의 합 : ", a+b)
print("두 수의 차 : ", a-b)
print("두 수의 곱 : ", a*b)
print("두 수의 평균 : ", (a+b)/2)
print("두 수 중 큰 수 : ", max(a, b))
print("두 수 중 작은 수 : ", min(a, b))
