weather = input("내일 전국의 날씨는? ")
SeoulMorning = input("내일 서울의 아침기온은? ")
JeonjuMorning = input("내일 전주의 아침기온은? ")
DaeguMorning = input("내일 대구의 아침기온은? ")
SeoulMidday = input("내일 서울의 한낮기온은? ")
DaejeonMidday = input("내일 대전의 한낮기온은? ")
BusanMidday = input("내일 부산의 한낮기온은? ")

print()
print("================================")
print("내일의 날씨입니다.")
print("내일 전국의 날씨는 ", weather, "입니다.")
print("아침기온은 서울이 ", SeoulMorning, ", 전주가 ", JeonjuMorning, ", 대구가 ", DaeguMorning, "이며")
print("한낮기온은 서울이 ", SeoulMidday, ", 전주가 ", DaejeonMidday, ", 대구가 ", BusanMidday, "가 되겠습니다.")
print("================================")
